#!/bin/sh
# open-selection.sh --system|--editor <pane-id> — act on one copy-mode selection safely.
# The selection arrives on STDIN from copy-pipe-and-cancel. Both modes trim the same untrusted
# text, keep only its first line, understand file:line[:column], and resolve relative paths from
# the source pane's cwd rather than from this helper or the tmux server.
#
# --system passes http/https URLs directly to open(1) or xdg-open(1). Every other target must be
# an existing path. --editor resolves $EDITOR at invocation time and opens the path in a new tmux
# window; a missing path is reported instead of becoming an empty editor buffer.
#
# THE SELECTION IS UNTRUSTED. It is whatever happened to be on screen. Never splice it, the pane
# id, the cwd, or an editor name into an unquoted shell fragment. The system opener receives one
# argv directly; the editor command is single-quoted with q() before tmux hands it to a shell.
set -u

say() {
  tmux display-message "open selection: $*" 2>/dev/null || true
}

mode=${1:-}
pane=${2:-}

[ "$#" -eq 2 ] || { say "usage: --system|--editor <pane-id>"; exit 1; }
case "$mode" in
  --system|--editor) ;;
  *) say "usage: --system|--editor <pane-id>"; exit 1 ;;
esac

# Pane IDs are generated by tmux as %<digits>. Reject target syntax, option-like values and shell
# punctuation before asking tmux to resolve the cwd.
case "$pane" in
  ''|'%'|%*[!0-9]*|[!%]*) say "invalid pane id"; exit 1 ;;
esac

dir=$(tmux display-message -p -t "$pane" '#{pane_current_path}' 2>/dev/null) || {
  say "pane no longer exists: $pane"
  exit 1
}
if [ -z "$dir" ] || [ ! -d "$dir" ]; then
  say "pane has no usable cwd: $pane"
  exit 1
fi

sel=$(cat)
[ -n "$sel" ] || { say "nothing selected"; exit 0; }

# One target per invocation. A multi-line selection means the first line is the interesting one.
sel=$(printf '%s\n' "$sel" | sed -n '1p')

# Trim whitespace and wrapping punctuation without using a broad [[:punct:]] class: that would
# turn /var/log/x into var/log/x. A trailing colon is safe to remove before file:line parsing
# because the structural colon sits before the numeric suffix, not at the end.
sel=$(printf '%s' "$sel" | sed \
  -e 's/^[[:space:]]*//' \
  -e 's/[[:space:]]*$//' \
  -e 's/^["'"'"'`([{<]*//' \
  -e 's/[]"'"'"'`)}>,;:.]*$//')
[ -n "$sel" ] || { say "nothing usable in the selection"; exit 0; }

# file:line[:column] is shared by both modes. URLs are excluded explicitly so a port such as
# https://localhost:8443 is never mistaken for an editor line number.
line=''
case "$sel" in
  http://*|https://*) ;;
  *)
    cand_line=$(printf '%s' "$sel" | sed -n 's/^.*:\([0-9][0-9]*\):[0-9][0-9]*$/\1/p')
    if [ -n "$cand_line" ]; then
      cand_file=$(printf '%s' "$sel" | sed 's/:[0-9][0-9]*:[0-9][0-9]*$//')
    else
      cand_line=$(printf '%s' "$sel" | sed -n 's/^.*:\([0-9][0-9]*\)$/\1/p')
      cand_file=$(printf '%s' "$sel" | sed 's/:[0-9][0-9]*$//')
    fi
    if [ -n "$cand_line" ] && [ -n "$cand_file" ]; then
      sel=$cand_file
      line=$cand_line
    fi
    ;;
esac

open_system() {
  if command -v open >/dev/null 2>&1; then
    open "$1"
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$1"
  else
    say "no system opener found"
    return 1
  fi
}

if [ "$mode" = --system ]; then
  case "$sel" in
    http://*|https://*) open_system "$sel"; exit $? ;;
  esac
fi

# Non-URL selections in both modes resolve against the source pane's directory and must exist.
case "$sel" in
  /*) target=$sel ;;
  '~') target=${HOME:-} ;;
  [~]/*) target="${HOME:-}/${sel#??}" ;;
  *) target="$dir/$sel" ;;
esac

if [ -z "$target" ] || [ ! -e "$target" ]; then
  say "not a path: $sel (looked in $dir)"
  exit 0
fi

if [ "$mode" = --system ]; then
  open_system "$target"
  exit $?
fi

# Resolve the editor NOW, not while tmux.conf is parsed. Treat the value as one executable name,
# never as a shell fragment with flags: command -v validates it, and q() quotes the resolved path.
editor=${EDITOR:-}
[ -n "$editor" ] || editor=$(tmux show-environment -g EDITOR 2>/dev/null | sed -n 's/^EDITOR=//p')
if [ -n "$editor" ]; then
  editor_path=$(command -v "$editor" 2>/dev/null) || {
    say "EDITOR is not an executable: $editor"
    exit 1
  }
elif command -v nvim >/dev/null 2>&1; then
  editor_path=$(command -v nvim)
elif command -v vi >/dev/null 2>&1; then
  editor_path=$(command -v vi)
else
  say "no editor found"
  exit 1
fi

q() { printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"; }

# `--` stops an option-like filename being read as an editor flag; +N is numeric and validated by
# the parser above, and must precede it. new-window still receives one safely quoted shell command.
if [ -n "$line" ]; then
  cmd="$(q "$editor_path") +$line -- $(q "$target")"
else
  cmd="$(q "$editor_path") -- $(q "$target")"
fi

tmux new-window -c "$dir" "$cmd"
